name: Create repos
on:
  workflow_dispatch:
    inputs:
      template_repo_fullname:
        description: "Template repo fullname in format: OrgName/RepoName"
        required: true
      org_name:
        description: "Name of organization with student repositories"
        required: true
        default: "INF1007-Test"
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
      num_repos:
        description: "Number of student repositories to create"
        required: true
        default: "10"
      admin_collaborators:
        description: "Collaborator usernames to receive admin access"
        default: "PolyINF1007"
      write_collaborators:
        description: "Collaborator usernames to receive write access"
        default: "PolyTestStudent0"

jobs:
  create_repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create repos
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ secrets.CLASSROOM_TOOLS_URL }}
          python3 -m create_repos \
            --token=${{ secrets.REPO_WORKFLOW_PAT }} \
            --template_repo_fullname=${{ github.event.inputs.template_repo_fullname }} \
            --org_name=${{ github.event.inputs.org_name }} \
            --repo_filter=${{ github.event.inputs.repo_filter }} \
            --num_repos=${{ github.event.inputs.num_repos }} \
            --admin_collaborators ${{ github.event.inputs.admin_collaborators }} \
            --write_collaborators ${{ github.event.inputs.write_collaborators }}
