name: Verifications

on:
  workflow_dispatch:
  push:

jobs:
  Secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Verify secrets
        run: |
          source settings/vars.txt
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+"$classroom_tools_url"
          python3 -m classroom_tools.verifications.access_to_github_secrets \
            --token=${{ secrets.REPO_ADMIN_PAT }} \
            --repo_fullname="$GITHUB_REPOSITORY"
